### ISSUE TITLE
How to limit or minimize overly broad search for Patient?

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/implementation-program#33]
Some servers will not support broad searches. For example, all patients born after 1900
Currently other than id, a minimum of 2 elements are required for all searches.

for example:
`GET [base]/Patient?name=[string]&gender=[code]`

But is even this Name and Gender too broad a search?  [further discussion](https://groups.google.com/forum/?hl=en#!topic/argonaut-fhir-data-query-team/8rmaYTAzF5A)

**Comment by brettmarquard** [comment]
During 3/22/2016 call team agreed to add the following:
 A client search with gender SHOULD include family and given.

**Comment by jmandel** [comment]
I've got to suggest that the "answer" to this question really depends on context. To give some concrete examples:
- for **patient apps**, we should allow broad queries, because the response will only include records that the patient-authorized app is allowed to see 
- for **clinician facing** apps, one goal is to support a "patient selector" widget -- how do we get there? 
  We need a discussion about this. But forcing a user to manually fill in three specific data fields will not lead to "delight" :-) I know @p2 and @rickybloomfield are passionate about this subject for mobile apps
- for backend apps and services... we need to understand the use cases better. But maybe restrictions make more sense here.

**Comment by rickybloomfield** [comment]
Yes, I'm passionate about this topic for provider-facing apps (mobile or otherwise, and it doesn't surprise me that @p2 shares that passion)! We need a standard entry point for the top level of a hierarchical list of lists (a concept employed by nearly every EHR vendor). Each list could contain other lists or discrete patients. Other nice-to-haves:
- a convention for a default list (indicated by the user, and displayed to the user first on app launch)
- lists could have a parameter indicating they are user-maintained or system-maintained

This would certainly help cut down the need for copious patient searches, and make provider-facing apps more relevant when the patient context isn't provided (e.g., mobile apps external to the EHR).

**Comment by Healthedata1** [comment]
Implementer to decide on approach -  document in IG.
