### ISSUE TITLE
Oxygen Saturation - 59408-5 (Pulse Oximetry) vs 2708-6 (no method)

### ISSUE THREAD

**Issue by brettmarquard** [argonautproject/implementation-program#43]
Originally C-CDA had: 2710-2 (now deprecated)
LOINC recommended: 59408-5 (SDWG agreed and approved, then reopened...)
HL7 Orders and Observation is recommending method less: 2708-6

No one objects to method less code (2708-6), what concerns folks is Class/type=CHEM/Lab. SDWG didn’t think Pulse Oximetry was appropriate with the method less code.

HL7 SDWG will discuss on their Thursday 6/16 conference call.

**Comment by Healthedata1** [comment]
O2 Saturations measures can be laboratory results or vital signs depending on method
 so the category could differentiate as well  

Meanwhile here are all the O2 sat LOINCS codes that are vitals.  All the rank=2 codes are OK as translations to the 59708-5 code.

| Rank | LOINC_NUM | LONG_COMMON_NAME | COMPONENT | METHOD_TYP | CLASS | PROPERTY | TIME_ASPCT | SCALE_TYP |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | 59408-5 | Oxygen saturation in Arterial blood by Pulse oximetry | Oxygen saturation | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59409-3 | Oxygen saturation in Arterial blood by Pulse oximetry --during treatment | Oxygen saturation^during treatment | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59410-1 | Oxygen saturation in Arterial blood by Pulse oximetry --on room air | Oxygen saturation^on room air | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59411-9 | Oxygen saturation in Arterial blood by Pulse oximetry --post bronchodilation | Oxygen saturation^post bronchodilation | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59412-7 | Oxygen saturation in Arterial blood by Pulse oximetry --post exercise | Oxygen saturation^post exercise | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59413-5 | Oxygen saturation in Arterial blood by Pulse oximetry --post treatment | Oxygen saturation^post treatment | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59414-3 | Oxygen saturation in Arterial blood by Pulse oximetry --pre bronchodilation | Oxygen saturation^pre bronchodilation | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59415-0 | Oxygen saturation in Arterial blood by Pulse oximetry --pre physiotherapy | Oxygen saturation^pre physiotherapy | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59416-8 | Oxygen saturation in Arterial blood by Pulse oximetry --pre treatment | Oxygen saturation^pre treatment | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59417-6 | Oxygen saturation in Arterial blood by Pulse oximetry --resting | Oxygen saturation^resting | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59418-4 | Oxygen saturation in Blood Postductal by Pulse oximetry | Oxygen saturation | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59407-7 | Oxygen saturation in Blood Preductal by Pulse oximetry | Oxygen saturation | Pulse oximetry | PULM | MFr | Pt | Qn |
| 2 | 59405-1 | Oxygen saturation in 8 hour maximum Arterial blood by Pulse oximetry | Oxygen saturation | Pulse oximetry | PULM | MFr | 8H^max | Qn |
| 2 | 59406-9 | Oxygen saturation in 8 hour minimum Arterial blood by Pulse oximetry | Oxygen saturation | Pulse oximetry | PULM | MFr | 8H^min | Qn |

**Comment by michelle-m-miller** [comment]
Some of the feedback/questions I am getting internally regarding this change:

The list is a comprehensive list for a component axis of “Oxygen saturation” and a method axis of “Pulse oximetry” (all challenges and dimensions included). I’d be curious to know why a method of “Pulse oximetry” is the deciding factor between vital and lab? Also, is the patients “Oxygen saturation” max/min over an 8 hour period really an acceptable substitute assuming that’s the only measurement you have taken by a pulse oximeter? Are any/all the challenge specific LOINCs on that list really acceptable substitutes?

It’s worth nothing that there are point of care devices that measure oxygen saturation on blood directly [1] that are not pulse oximeters. I expect measurements taken with one of these devices would probably be mapped to a methodless LOINC or a new yet to be created method specific LOINC. For the purposes of inter-op, wouldn’t returning a value taken by that device on the vitals panel be more/equally appropriate than the max value taken by a pulse oximeter over an 8 hour period?

[1]  https://www.abbottpointofcare.com/products-services/istat-handheld

**Comment by Healthedata1** [comment]
These are great questions.  They are clinical in nature and really
shouldn't be decided here.   But the underlying issue is categorizing a
laboratory measure as a vital sign.  Why is blood measurement a vital and
not a lab?  I can go either way on this. On the one hand there is the
desire to align with c-cda and the Structured Doc work group decision and I
think pulse ox o2 can be considered a vital due to its ubiquity.   On the
other hand, if we are trying to keep the concept of O2 saturation pretty
generic and methodless - I think if the _category *is vitals then its
likely a pulse ox measurement, if its *laboratory_ then somebody got jabbed
with needle and a direct measure on blood was taken.  But that clinical
decision should be made by each organization or institution. Personally, I
don't think we can have a measure that is both a vital and a lab. Then the
search by category vitals would probably get you them same thing in either
case.

Eric

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by michelle-m-miller** [comment]
I know I asked for clarity on what all should be returned for this, but I am questioning could/should it be defined via “rules” rather than a specific list?  The “rules” might look something like this: http://search.loinc.org/search.zul?query=component%3A%22oxygen+saturation%22+property%3A%22mfr%22+scale%3A%22qn%22+method%3A%22pulse+oximetry%22.  
- Pro—the profile isn’t bound to a particular version of LOINC.  New LOINCs meeting the criteria are automatically a part of the profile spec.  
- Con -- what’s the risk that a new LOINC meets whatever criteria defined, but still is undesirable to “roll up” to 59408-5?

**Comment by Healthedata1** [comment]
Either way works for me.  Still awaiting the SD discussion....

Eric M Haas, DVM, MS
Health eData Inc
211 South Jefferson Street, Napa, CA, 94559
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com ehaas@healhtedatainc.com

**Comment by Healthedata1** [comment]
final decision by Structured Documents (SD) was 59408-5

**Comment by brettmarquard** [comment]
[SDWG Vote](http://www.hl7.org/dstucomments/showdetail_comment.cfm?commentid=986)
