### ISSUE TITLE
Proper Argonaut extension code system

### ISSUE THREAD

**Issue by brettmarquard** [argonautproject/implementation-program#58]
We did some clean-up to use http://argonaut.hl7.org but never confirmed with team. Also, what is process when something moves to 'us-core' extension? For example, condition category codes.

**Comment by daliboz** [comment]
It would be nice to not have to change this (eg: when it does move), since it's technically non-passive to existing deployments. However, assuming the us-core change will happen with the STU 3 uplift with the official migration of DAF to US Core, that's not as much of a concern.

What are servers using right now for the system on these codes? Is it the unqualified argonaut one? or the one under the extensions URL?

**Comment by brettmarquard** [comment]
For Argonaut, we will stick with http://argonaut.hl7.org until someone takes a stance for something different. For US-core, we are planning the following:
- http://hl7.org/fhir/us-core/
- http://hl7.org/fhir/us-core/condition-category
- http://hl7.org/fhir/us-core/careplan-category

Please let us know if we are getting too creative.

**Comment by daliboz** [comment]
@brettmarquard The unqualified one is not what we're currently returning, since I think we implemented prior to that change. Would want to make sure everyone is good with that (I think that's what this issue is for) before switching it...

**Comment by brettmarquard** [comment]
Got-it. No problem with us either way.

**Comment by Healthedata1** [comment]
have discussed and fixed for both published IGs
